services:
  mongo1:
    env_file:
      - ../../.env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mongo1
    ports:
      - 27017:27017
    environment:
      PORT: 27017
    volumes:
      - ./data/mongo1:/data/db
      - ./config/mongo1:/data/configdb

  mongo2:
    env_file:
      - ../../.env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mongo2
    ports:
      - 27018:27018  
    environment:
      PORT: 27018
    volumes:
      - ./data/mongo2:/data/db
      - ./config/mongo2:/data/configdb

  mongo3:
    env_file:
      - ../../.env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mongo3
    ports:
      - 27019:27019
    environment:
      PORT: 27019
    volumes:
      - ./data/mongo3:/data/db
      - ./config/mongo3:/data/configdb

  init-mongo:
    env_file:
      - ../../.env
    image: mongo:7.0
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    volumes:
      - ./init-replica.sh:/init-replica.sh:ro
    entrypoint: ["/bin/sh", "/init-replica.sh"]
